# Generated by Django 2.2.5 on 2020-02-18 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='candidate',
            new_name='constituency',
        ),
    ]
